#!/usr/bin/env python3
"""Every condition ever run, what it did, and what it scored.

    python scripts/build_method_registry.py > METHODS_TRIED.md

Each round used its own requirement set, its own prompt and sometimes its own
model, so the numbers are only comparable *within* a round. They are therefore
reported per round, each against that round's own baseline, and no cross-round
table is produced -- a mean-violations figure from round 2 and one from round 15
are counts of different things.

Scores come from the per-condition file each run wrote at the time, which was
computed under the requirement set in force then. Recomputing them now would
silently re-score old stories against rules they were never asked to follow.
"""
import csv
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))


def scores(round_dir):
    """label -> (n, broken, vendi) from every score file the round left behind."""
    out = {}
    for f in glob.glob(os.path.join(round_dir, "**", "live_scores.csv"), recursive=True):
        for row in csv.DictReader(open(f)):
            try:
                out[row["run"]] = (row.get("label", ""), int(row["n"]),
                                   float(row["mean_violations"]), float(row["vendi"]))
            except (KeyError, ValueError):
                continue
    return out


def runs(round_dir):
    out = {}
    for f in glob.glob(os.path.join(round_dir, "**", "state.json"), recursive=True):
        for rid, cells in json.load(open(f)).get("runs", {}).items():
            out.setdefault(rid, 0)
            out[rid] = max(out[rid], len(cells))
    return out


# What each tag in a run id means, in words. This is the index of every mechanism
# the project has actually put on a GPU.
MECHANISMS = [
    ("BASELINE", "unmodified generation"),
    ("temp", "raised sampling temperature"),
    ("topp", "nucleus (top-p) cut-off"),
    ("topk", "top-k cut-off"),
    ("ORTHO", "constraint steering in the residual stream"),
    ("lowdin", "constraint directions made mutually orthogonal (Lowdin)"),
    ("bud", "total push held to a fixed budget, so the number of requirements "
            "stops setting the strength"),
    ("smerror", "push strength set by the constraint error measured on the text so far"),
    ("smfeedback", "push strength set by a shortfall measured in activation space"),
    ("nzorth", "fresh noise at every decode step, projected clear of the constraint "
               "directions"),
    ("nzfree", "fresh noise at every decode step, not projected clear"),
    ("nznone", "no per-step noise"),
    ("orth", "perturbation projected clear of the constraint directions"),
    ("free", "perturbation NOT projected clear (ablation)"),
    ("obstory", "per-story offset drawn from the subspace along which whole stories differ"),
    ("obprompt", "per-story offset drawn from the prompt subspace"),
    ("obstep", "per-story offset drawn from the step subspace"),
    ("opre", "perturbation applied at the prompt positions"),
    ("ponly", "perturbation at the prompt only, nothing while writing"),
    # The magnitude sits in the middle of these tags -- "j0p6gain", not "jgain" --
    # so they are matched by pattern. Spelling them as plain substrings reported
    # the whole f(S) family as never run when eleven conditions had used it.
    (r"j[\dp]+perp", "sideways step added to the constraint vector (f(S), dose grows)"),
    (r"j[\dp]+rotate", "constraint vector turned, length preserved (f(S), dose fixed)"),
    (r"j[\dp]+gain", "requirements re-weighted per story (f(S), stays in the "
                     "constraint span)"),
    (r"j[\dp]+frame", "directions moved before being made orthogonal (f(S) on the frame)"),
    ("sch", "a schedule on the push or the noise (cosine decay, prefix, ramp, tail)"),
    ("gate", "perturb only the decode steps where the model is uncertain"),
    ("randdir", "random directions instead of extracted ones (control)"),
    ("prefill", "the constraint push applied to the prompt as well as the story"),
]


def mechanisms_in(rid):
    return [d for t, d in MECHANISMS if re.search(t, rid)]


def main():
    rounds = sorted(d for d in glob.glob(os.path.join(ROOT, "experiments", "*"))
                    if os.path.isdir(d))
    print("# Everything already tried\n")
    print("Generated by `scripts/build_method_registry.py`. One section per round.\n")
    print("**Numbers are comparable only within a round.** Each round used its own "
          "requirement set, prompt and sometimes its own model, so a broken-requirement "
          "count from one round and one from another are counts of different things. "
          "Scores are the ones each run computed at the time, under the rules in force "
          "then; recomputing now would score old stories against rules they were never "
          "asked to follow.\n")
    print("`broken` is requirements failed per story, lower better. `Vendi` is the "
          "effective number of distinct stories in the set, higher better.\n")

    seen_mech = {}
    for d in rounds:
        name = os.path.basename(d)
        sc, rs = scores(d), runs(d)
        if not rs:
            continue
        print(f"\n## {name}\n")
        rows = []
        for rid, n in rs.items():
            label, sn, broken, vendi = sc.get(rid, ("", n, float("nan"), float("nan")))
            rows.append((label or rid, sn or n, broken, vendi, rid))
            for m in mechanisms_in(rid):
                seen_mech.setdefault(m, []).append(name)
        rows.sort(key=lambda r: (r[2] != r[2], r[2]))
        print(f"| condition | n | broken | Vendi |")
        print(f"|---|---|---|---|")
        for label, n, broken, vendi, rid in rows:
            b = "-" if broken != broken else f"{broken:.2f}"
            v = "-" if vendi != vendi else f"{vendi:.2f}"
            print(f"| {label[:78]} | {n} | {b} | {v} |")

    print("""

## What the rounds have settled

These are the conclusions the tables above support. They are written here so a
mechanism is not rebuilt because its result was forgotten.

**Steering buys compliance and spends diversity.** Holding the constraint push to
a fixed budget takes the monotone requirements from 25% to 66% and takes Vendi
from 7.56 down to 6.17. Every steered arm across every round sits below its own
baseline on diversity.

**Perturbation does the reverse**, and the exchange rate is roughly one
requirement per unit of diversity bought.

**Holding the dose fixed holds the diversity fixed too.** Turning the constraint
vector without changing its length moved Vendi by +0.12; re-weighting the
requirements at a fixed total push moved it by -0.43. Both are near-nulls. The
diversity only ever arrived when perturbation *energy* was added off the
constraint subspace -- the sideways step, which grows the dose, bought +1.11
Vendi for +0.42 requirements. There is no free lunch in re-aiming a push of
constant length, and an arm that claims one should be checked against this.

**The best trade found so far** is a per-story perturbation applied at the prompt
positions, drawn from the subspace along which whole stories differ and projected
clear of the constraint directions: about +1.1 Vendi for +0.4 requirements.

**Banded requirements cannot be steered.** Across thirty-six steered conditions,
none improved a requirement of the form "between N and M" over leaving the model
alone. A constant push has no notion of enough. Measuring the error on the
decoded text and scaling the push by it reduces the damage about fivefold but
does not remove it. This is why the main comparison moved to requirements that
are all one-sided.

**The model as it ships is not a strong baseline.** At its default settings it
loops on 32% of stories for this prompt, which inflates its broken count and
holds its Vendi to 6.94. Temperature 1.8 with top-k 40 stops the looping and
beats the default on both axes at once: 7.21 broken and Vendi 10.65. That, not
the default, is the number a method has to beat.

**Two measurement faults were found and fixed**, and old numbers carry them.
Qwen3 ships top_p in its generation config, so an arm that does not set it
inherits it -- a "plain" baseline was really top-p 0.95. And a sharded run's
per-condition scores were written per GPU and one overwrote the other, so half
the diversity numbers went missing.
""")

    print("\n\n## Mechanisms that have been run, and where\n")
    print("| mechanism | rounds |")
    print("|---|---|")
    for m in [d for _, d in MECHANISMS]:
        where = seen_mech.get(m)
        if where:
            print(f"| {m} | {', '.join(sorted(set(where)))} |")
    print("\n### Implemented but never run on a GPU\n")
    for m in [d for _, d in MECHANISMS]:
        if m not in seen_mech:
            print(f"- {m}")


if __name__ == "__main__":
    main()
