#!/usr/bin/env python3
"""Every condition ever run, what it did, and what it scored.

    python scripts/build_method_registry.py > METHODS_TRIED.md

Each round used its own requirement set, its own prompt and sometimes its own
model, so the numbers are only comparable *within* a round. They are therefore
reported per round, each against that round's own baseline, and no cross-round
table is produced -- a mean-violations figure from round 2 and one from round 15
are counts of different things.

Scores come from the per-condition file each run wrote at the time, which was
computed under the requirement set in force then. Recomputing them now would
silently re-score old stories against rules they were never asked to follow.
"""
import csv
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))


def scores(round_dir):
    """label -> (n, broken, vendi) from every score file the round left behind."""
    out = {}
    for f in glob.glob(os.path.join(round_dir, "**", "live_scores.csv"), recursive=True):
        for row in csv.DictReader(open(f)):
            try:
                out[row["run"]] = (row.get("label", ""), int(row["n"]),
                                   float(row["mean_violations"]), float(row["vendi"]))
            except (KeyError, ValueError):
                continue
    return out


def runs(round_dir):
    out = {}
    for f in glob.glob(os.path.join(round_dir, "**", "state.json"), recursive=True):
        for rid, cells in json.load(open(f)).get("runs", {}).items():
            out.setdefault(rid, 0)
            out[rid] = max(out[rid], len(cells))
    return out


# What each tag in a run id means, in words. This is the index of every mechanism
# the project has actually put on a GPU.
MECHANISMS = [
    ("BASELINE", "unmodified generation"),
    ("temp", "raised sampling temperature"),
    ("topp", "nucleus (top-p) cut-off"),
    ("topk", "top-k cut-off"),
    ("ORTHO", "constraint steering in the residual stream"),
    ("lowdin", "constraint directions made mutually orthogonal (Lowdin)"),
    ("bud", "total push held to a fixed budget, so the number of requirements "
            "stops setting the strength"),
    ("smerror", "push strength set by the constraint error measured on the text so far"),
    ("smfeedback", "push strength set by a shortfall measured in activation space"),
    ("nzorth", "fresh noise at every decode step, projected clear of the constraint "
               "directions"),
    ("nzfree", "fresh noise at every decode step, not projected clear"),
    ("nznone", "no per-step noise"),
    ("orth", "perturbation projected clear of the constraint directions"),
    ("free", "perturbation NOT projected clear (ablation)"),
    ("obstory", "per-story offset drawn from the subspace along which whole stories differ"),
    ("obprompt", "per-story offset drawn from the prompt subspace"),
    ("obstep", "per-story offset drawn from the step subspace"),
    ("opre", "perturbation applied at the prompt positions"),
    ("ponly", "perturbation at the prompt only, nothing while writing"),
    # The magnitude sits in the middle of these tags -- "j0p6gain", not "jgain" --
    # so they are matched by pattern. Spelling them as plain substrings reported
    # the whole f(S) family as never run when eleven conditions had used it.
    (r"j[\dp]+perp", "sideways step added to the constraint vector (f(S), dose grows)"),
    (r"j[\dp]+rotate", "constraint vector turned, length preserved (f(S), dose fixed)"),
    (r"j[\dp]+gain", "requirements re-weighted per story (f(S), stays in the "
                     "constraint span)"),
    (r"j[\dp]+frame", "directions moved before being made orthogonal (f(S) on the frame)"),
    ("sch", "a schedule on the push or the noise (cosine decay, prefix, ramp, tail)"),
    ("gate", "perturb only the decode steps where the model is uncertain"),
    ("randdir", "random directions instead of extracted ones (control)"),
    ("prefill", "the constraint push applied to the prompt as well as the story"),
]


def mechanisms_in(rid):
    return [d for t, d in MECHANISMS if re.search(t, rid)]


def main():
    rounds = sorted(d for d in glob.glob(os.path.join(ROOT, "experiments", "*"))
                    if os.path.isdir(d))
    print("# Everything already tried\n")
    print("Generated by `scripts/build_method_registry.py`. One section per round.\n")
    print("**Numbers are comparable only within a round.** Each round used its own "
          "requirement set, prompt and sometimes its own model, so a broken-requirement "
          "count from one round and one from another are counts of different things. "
          "Scores are the ones each run computed at the time, under the rules in force "
          "then; recomputing now would score old stories against rules they were never "
          "asked to follow.\n")
    print("`broken` is requirements failed per story, lower better. `Vendi` is the "
          "effective number of distinct stories in the set, higher better.\n")

    seen_mech = {}
    for d in rounds:
        name = os.path.basename(d)
        sc, rs = scores(d), runs(d)
        if not rs:
            continue
        print(f"\n## {name}\n")
        rows = []
        for rid, n in rs.items():
            label, sn, broken, vendi = sc.get(rid, ("", n, float("nan"), float("nan")))
            rows.append((label or rid, sn or n, broken, vendi, rid))
            for m in mechanisms_in(rid):
                seen_mech.setdefault(m, []).append(name)
        rows.sort(key=lambda r: (r[2] != r[2], r[2]))
        print(f"| condition | n | broken | Vendi |")
        print(f"|---|---|---|---|")
        for label, n, broken, vendi, rid in rows:
            b = "-" if broken != broken else f"{broken:.2f}"
            v = "-" if vendi != vendi else f"{vendi:.2f}"
            print(f"| {label[:78]} | {n} | {b} | {v} |")

    print("""

## Numbers that recur across rounds

Collected so a mechanism is not rebuilt because its result was forgotten. These
are results, not conclusions, and each is from the configuration named beside it.
`RESEARCH_STATE.md` gives the setups in full; the configurations differ between
rounds in ways that can carry a result.

**Constraint push, Qwen3-1.7B, layers 10-18.** On the 13 one-sided requirements at
100 stories: 7.78 broken unsteered, 5.99 at a total push of 1.5, 4.71 at 3, 3.83 at
4.5, with looping falling from 32% to 21%. Vendi over the same arms fell from 6.93
to 5.67. On the mixed sets the one-sided requirements in them went 25% to 64-66%
and the banded ones 23% to 3%.

**Perturbation alone, same configuration, 100 stories.** Vendi 6.93 to 9.94 at
gamma 0.1 and 12.71 at 0.15; broken 7.78 to 7.08 and 7.83 respectively.

**Both together, same configuration, 100 stories.** Push 3 with gamma 0.1: 3.72
broken and Vendi 8.26. With gamma 0.15: 3.84 and 9.56.

**Perturbing the constraint vector at unchanged length, Qwen3-8B, layers 14-22, 12
mixed requirements, 40 stories, no steering budget.** Turning it: 5.03 broken and
Vendi 4.15 against a baseline of 4.55 and 4.03. Re-weighting the requirements: 5.15
and 3.60. Adding a perpendicular step, which does lengthen the push: 4.97 and 5.14
at kappa 0.1, 5.95 and 6.59 at 0.15. Only the re-weighting has been repeated on
Qwen3-1.7B (r15, budget 3, one-sided set: 5.33 broken against 4.71 without it).

**Choosing the perturbation set by repulsion instead of drawing each
independently, Qwen3-1.7B, 100 stories, four matched pairs.** 9.94 to 9.68, 12.71
to 11.94, 8.26 to 7.95, 9.56 to 8.81.

**Banded requirements under 36 steered conditions, Qwen3-1.7B, rounds 7-14.** 23%
unsteered; 3% under a constant push; 9-14% with the coefficient scaled by the error
measured on the partial decoded text. Two conditions of the 36 came in at 24%.

**Decoding parameters, Qwen3-1.7B, no steering, 100 stories, Vendi untruncated.**
The model at its defaults: 7.78 broken, Vendi 6.94, looping 32%. Temperature 1.8
with top-k 40: 7.21, 10.65, 6%.

**Two measurement faults were found and fixed, and older numbers carry them.**
Qwen3 ships top_p in its generation config, so a condition that does not set it
inherits it and a "plain" baseline was really top-p 0.95. And a sharded run wrote
per-condition scores per GPU with one overwriting the other, so half the diversity
numbers were missing.
""")

    print("\n\n## Mechanisms that have been run, and where\n")
    print("| mechanism | rounds |")
    print("|---|---|")
    for m in [d for _, d in MECHANISMS]:
        where = seen_mech.get(m)
        if where:
            print(f"| {m} | {', '.join(sorted(set(where)))} |")
    print("\n### Implemented but never run on a GPU\n")
    for m in [d for _, d in MECHANISMS]:
        if m not in seen_mech:
            print(f"- {m}")


if __name__ == "__main__":
    main()
